---
services: docker
sudo: required
language: python
python:
  - '2.7'

env:
  - APB_NAME=nuxeo-dev-apb OPENSHIFT_VERSION=v3.9

script:
  # Configure test values
  - export apb_name=$APB_NAME
  - cd $TRAVIS_BUILD_DIR/$APB_NAME

  # Download test shim.
  - wget -O ${PWD}/apb-test.sh https://raw.githubusercontent.com/ansibleplaybookbundle/apb-test-shim/master/apb-test.sh
  - chmod +x ${PWD}/apb-test.sh

  # Run tests.
  - ${PWD}/apb-test.sh
