- name: Playbook to deprovision a Nuxeo dev environment
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-dev-apb
  vars:
    apb_action: deprovision