---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster


- name: "Set fact admin_password state={{ state }}"
  set_fact:
    nexus_password: "{{ password_lookup if nexus_admin_password is undefined else nexus_admin_password }}"

- name: "Set CI/CD objects state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.apply | default(True)
  loop:
    - name: nexus_service.yml.j2
    - name: nexus_route.yml.j2
    - name: nexus_config.yml.j2
    - name: nexus_creds.yml.j2
    - name: nexus_pv.yml.j2
    - name: nexus_dc.yml.j2

- name: "Wait for Deployment to become ready"
  debug:
    msg: "DeploymentConfig ready status: {{ dc_query }}"
  retries: 20
  delay: 10
  until:
    - dc_query
  when: state == 'present'

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Cluster objects state={{ state }}"
  when: in_cluster