---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster


- name: "Set Nuxeo Dev global objects state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.apply | default(True)
  loop:
    - name: global-config.yml.j2
    - name: connect-secret.yml.j2
    - name: connect-secret-basic.yml.j2

- name: "Instantiating backend storage"
  include_tasks: "backend_storage.yml"
  # As it requires APB and Ansible Service catalog
  # we do not run that part in test
  when: not testing

- name: "Instantiating Nuxeo deployments"
  include_tasks: "nuxeo_deployment.yml"
  # As it requires APB and Ansible Service catalog
  # we do not run that part in test
  # when: not testing

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Cluster objects state={{ state }}"
  when: in_cluster